global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'module-fundamentals'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'module-fundamentals-challenge'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'module2-apis'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8083']